name: evently
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# App version
version: 1.0.0+1

environment:
  # Dart SDK version compatible with Flutter 3
  sdk: ">=3.0.0 <4.0.0"

# ----------------------------
# Dependencies used in project
# ----------------------------
dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons (iOS style)
  cupertino_icons: ^1.0.8

# ----------------------------
# Dev dependencies (for testing, linting, tools)
# ----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules
  flutter_lints: ^5.0.0

  # Splash screen generator
  flutter_native_splash: ^2.4.6

# ----------------------------
# Flutter section
# ----------------------------
flutter:
  # Ensures Material Icons are included
  uses-material-design: true

  assets:
    - assets/images/

  # Example for adding assets (uncomment and edit if you need)
  
  # Example for custom fonts (uncomment and edit if you need)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic